---

roles:
  - name: geerlingguy.pip
    scm: git
    src: https://github.com/geerlingguy/ansible-role-pip.git
    version: origin/master


# https://docs.ansible.com/ansible/latest/collections/index.html#list-of-collections
collections:

  # https://docs.ansible.com/ansible/latest/collections/amazon/aws/index.html
  - name: https://github.com/ansible-collections/amazon.aws.git
    type: git

  # https://docs.ansible.com/ansible/latest/collections/azure/azcollection/index.html
  - name: https://github.com/ansible-collections/azure.git
    type: git

  # https://docs.ansible.com/ansible/latest/collections/community/general/index.html
  - name: https://github.com/ansible-collections/community.general.git
    type: git
    
    # https://docs.ansible.com/ansible/latest/collections/community/docker/index.html
  - name: https://github.com/ansible-collections/community.docker.git
    type: git
  